{% set name = "plothist_utils" %}
{% set version = "0.0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plothist_utils-{{ version }}.tar.gz
  sha256: f2b4ed4ea28b548a002fc9bd9760bd10d743f942d215a9627e6b351004a4b749

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.14.5

test:
  imports:
    - plothist_utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/8-hat/plothist_utils
  summary: Utilities for the plothist package
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 0ctagon
